### ISSUE TITLE
Enabiling EM on REDCap 8.1.1

### ISSUE THREAD

**Issue by taber13** [susom/redcap-em-imagemap#1]
Issue when enabling EM.  REDCap Version 8.1.1

First had to rename folder and add "_v1.0" for it to show up in "Enable a Module"

When I try to enable, get the error below.

"Exception while enabling module: The file 'ImageMap.php' file must define the '\Stanford\ImageMap\ImageMap' class for the 'redcap-em-imagemap-master' module.
This module requests the following permissions:

redcap_every_page_top"

Seems to be missing something..

**Comment by 123andy** [comment]
Hello Taber13,

This is not intended for general use yet as it hasn't been released to the REDCap consortium.  It is still under development.

-A

**Comment by taber13** [comment]
Ok, sorry about that..

**Comment by 123andy** [comment]
Hi @taber13 - just posted updates to a different repo you could try:

https://github.com/susom/painmap

Download and rename to: /modules/imagemap_v0.0
I use 0.0 to signify that this is a git-repo and not a redcap 'app store' module.

-A
